### ISSUE TITLE
Uruguay

### ISSUE THREAD

**Issue by vradelet2602** [vradelet2602/Patagonia#2]
Il faudrait se renseigner sur MonteVideo. Le mieux serait probablement de commencer par faire le compte des jours qu'on aimerait passer ca et la puis aviser. Niveau budget et temps, soit c'est vraiment un incontournable soit on a des jours a tuer.

**Comment by emmalunelle** [comment]
C'est plus Colonia qui vaudrait la peine à ce qu'il paraît. Tant mieux car c'est plus proche.
En ce qui me concerne, je devrai faire renouveler mon visa de 3 mois ici donc, j'y passerai un moment où l'autre. :-)

Sinon, Dans le genre excursion romantique Depuis Buenos Aires : Tigre est appelée la Venise Argentine. ;)
